version: "3"
networks:
  app:
services:
  db:
    networks:
      - app
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - 33060:3306
    volumes:
    - ".docker/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  db-test:
    networks:
      - app
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33061:3306
    volumes:
      - ".docker/db-test:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  app:
    depends_on:
      - db
    networks:
      - app
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      NODE_ENV: docker
      DB_HOST: db
      DB_PORT: 3306
    ports:
    - 8000:8000
    volumes:
    - ".:/var/app"
    working_dir: "/var/app"
    entrypoint: yarn dev

